---
- name: Remove Nginx from Ubuntu
  hosts: all  # Replace with your host group or IP addresses
  become: yes            # Use sudo to run commands
  tasks:

    - name: Stop Nginx service
      systemd:
        name: nginx
        state: stopped
        enabled: no

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent

    - name: Remove additional Nginx-related packages
      apt:
        name:
          - nginx-common
          - nginx-full
          - nginx-core
          - nginx-light
          - nginx-extras
        state: absent

    - name: Remove any unused dependencies (autoremove)
      apt:
        autoremove: yes
        state: absent

    - name: Remove Nginx configuration files
      file:
        path: /etc/nginx
        state: directory
        recurse: yes

    - name: Remove Nginx log files
      file:
        path: /var/log/nginx
        state: directory
        recurse: yes

    - name: Remove Nginx cache files
      file:
        path: /var/cache/nginx
        state: directory
        recurse: yes

    - name: Remove Nginx user
      user:
        name: nginx
        state: absent

    - name: Remove Nginx group
      group:
        name: nginx
        state: absent

