---
- name: Install the latest version of Nginx on Ubuntu
  hosts: all  # Replace with your host group or IP addresses
  become: yes            # Use sudo to run commands
  tasks:

    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install dependencies for adding external repositories
      apt:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add the official Nginx repository (if needed)
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add the Nginx APT repository
      apt_repository:
        repo: "deb http://nginx.org/packages/mainline/ubuntu noble nginx"
        state: present
        filename: "nginx"

    - name: Install the latest version of Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure Nginx is started and enabled at boot
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: copy the domain file and restart nginx
      copy:
        src:  ../index.html
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted